version: '3.8'
services:
  minio:
    build: .
    container_name: minio1
    ports:
      - "9000:9000"  # Port for MinIO API
      - "9001:9001"  # Port for MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data  # Maps the volume minio_data to /data in the container

volumes:
  minio_data:
